export type Country = { code: string; name: string; nameEn: string }

export const countries: Country[] = [
  // Américas hispanohablantes primero
  { code: 'AR', name: 'Argentina', nameEn: 'Argentina' },
  { code: 'BO', name: 'Bolivia', nameEn: 'Bolivia' },
  { code: 'CL', name: 'Chile', nameEn: 'Chile' },
  { code: 'CO', name: 'Colombia', nameEn: 'Colombia' },
  { code: 'CR', name: 'Costa Rica', nameEn: 'Costa Rica' },
  { code: 'CU', name: 'Cuba', nameEn: 'Cuba' },
  { code: 'DO', name: 'República Dominicana', nameEn: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador', nameEn: 'Ecuador' },
  { code: 'SV', name: 'El Salvador', nameEn: 'El Salvador' },
  { code: 'GT', name: 'Guatemala', nameEn: 'Guatemala' },
  { code: 'HN', name: 'Honduras', nameEn: 'Honduras' },
  { code: 'MX', name: 'México', nameEn: 'Mexico' },
  { code: 'NI', name: 'Nicaragua', nameEn: 'Nicaragua' },
  { code: 'PA', name: 'Panamá', nameEn: 'Panama' },
  { code: 'PY', name: 'Paraguay', nameEn: 'Paraguay' },
  { code: 'PE', name: 'Perú', nameEn: 'Peru' },
  { code: 'PR', name: 'Puerto Rico', nameEn: 'Puerto Rico' },
  { code: 'UY', name: 'Uruguay', nameEn: 'Uruguay' },
  { code: 'VE', name: 'Venezuela', nameEn: 'Venezuela' },
  // España y Portugal
  { code: 'ES', name: 'España', nameEn: 'Spain' },
  { code: 'PT', name: 'Portugal', nameEn: 'Portugal' },
  // Brasil
  { code: 'BR', name: 'Brasil', nameEn: 'Brazil' },
  // EE.UU. y Canadá
  { code: 'US', name: 'Estados Unidos', nameEn: 'United States' },
  { code: 'CA', name: 'Canadá', nameEn: 'Canada' },
  // Europa
  { code: 'DE', name: 'Alemania', nameEn: 'Germany' },
  { code: 'AT', name: 'Austria', nameEn: 'Austria' },
  { code: 'BE', name: 'Bélgica', nameEn: 'Belgium' },
  { code: 'HR', name: 'Croacia', nameEn: 'Croatia' },
  { code: 'DK', name: 'Dinamarca', nameEn: 'Denmark' },
  { code: 'SK', name: 'Eslovaquia', nameEn: 'Slovakia' },
  { code: 'SI', name: 'Eslovenia', nameEn: 'Slovenia' },
  { code: 'FI', name: 'Finlandia', nameEn: 'Finland' },
  { code: 'FR', name: 'Francia', nameEn: 'France' },
  { code: 'GR', name: 'Grecia', nameEn: 'Greece' },
  { code: 'HU', name: 'Hungría', nameEn: 'Hungary' },
  { code: 'IE', name: 'Irlanda', nameEn: 'Ireland' },
  { code: 'IT', name: 'Italia', nameEn: 'Italy' },
  { code: 'LU', name: 'Luxemburgo', nameEn: 'Luxembourg' },
  { code: 'NO', name: 'Noruega', nameEn: 'Norway' },
  { code: 'NL', name: 'Países Bajos', nameEn: 'Netherlands' },
  { code: 'PL', name: 'Polonia', nameEn: 'Poland' },
  { code: 'RO', name: 'Rumanía', nameEn: 'Romania' },
  { code: 'RU', name: 'Rusia', nameEn: 'Russia' },
  { code: 'SE', name: 'Suecia', nameEn: 'Sweden' },
  { code: 'CH', name: 'Suiza', nameEn: 'Switzerland' },
  { code: 'TR', name: 'Turquía', nameEn: 'Turkey' },
  { code: 'UA', name: 'Ucrania', nameEn: 'Ukraine' },
  { code: 'GB', name: 'Reino Unido', nameEn: 'United Kingdom' },
  { code: 'CZ', name: 'República Checa', nameEn: 'Czech Republic' },
  // Asia
  { code: 'CN', name: 'China', nameEn: 'China' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', nameEn: 'United Arab Emirates' },
  { code: 'IN', name: 'India', nameEn: 'India' },
  { code: 'ID', name: 'Indonesia', nameEn: 'Indonesia' },
  { code: 'IL', name: 'Israel', nameEn: 'Israel' },
  { code: 'JP', name: 'Japón', nameEn: 'Japan' },
  { code: 'KZ', name: 'Kazajistán', nameEn: 'Kazakhstan' },
  { code: 'MY', name: 'Malasia', nameEn: 'Malaysia' },
  { code: 'PH', name: 'Filipinas', nameEn: 'Philippines' },
  { code: 'SG', name: 'Singapur', nameEn: 'Singapore' },
  { code: 'KR', name: 'Corea del Sur', nameEn: 'South Korea' },
  { code: 'TH', name: 'Tailandia', nameEn: 'Thailand' },
  { code: 'VN', name: 'Vietnam', nameEn: 'Vietnam' },
  // África
  { code: 'ZA', name: 'Sudáfrica', nameEn: 'South Africa' },
  { code: 'NG', name: 'Nigeria', nameEn: 'Nigeria' },
  { code: 'MA', name: 'Marruecos', nameEn: 'Morocco' },
  { code: 'EG', name: 'Egipto', nameEn: 'Egypt' },
  // Oceanía
  { code: 'AU', name: 'Australia', nameEn: 'Australia' },
  { code: 'NZ', name: 'Nueva Zelanda', nameEn: 'New Zealand' },
  // Otros
  { code: 'OTHER', name: 'Otro', nameEn: 'Other' },
]
